---
application:
  name: "titanbot"
  project: "TitanBot"
  organization: "QoveryCommunity"
databases:
- type: "REDIS"
  name: "prices"
  version: "6"
routers:
- name: "main-titanbot"
  routes:
  - application_name: "titanbot"
    paths:
    - "/*"
